name: svgtool

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  uses-material-design: true
  assets:
    - bundle/images/
    - bundle/images/icons/
    - bundle/images/placeholder/
    - bundle/images/console/

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  uuid: ^4.5.0
  url_strategy: ^0.3.0
  validators: ^3.0.0
  split_view: ^3.2.1
  flutter_screenutil: ^5.9.3
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  loading_indicator: ^3.1.1
  go_router: ^14.2.7
  logger: ^2.4.0
  path_provider: ^2.1.4
  freezed_annotation: ^2.4.4
  assorted_layout_widgets: ^9.0.2

dev_dependencies:
  flutter_lints:
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  freezed: ^2.5.7
