name: polaris

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  uses-material-design: true
  assets:
    - bundle/images/
    - bundle/images/icons/
    - bundle/images/placeholder/
    - bundle/images/console/

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.1
  path: ^1.8.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  flutter_svg: ^2.0.10+1
  uuid: ^4.3.3
  syncfusion_flutter_datepicker:
  syncfusion_flutter_calendar:
  url_strategy: ^0.2.0
  validators: ^3.0.0
  split_view: ^3.1.0
  flutter_riverpod: ^2.0.0
  flutter_screenutil: ^5.5.4
  json_annotation: ^4.7.0
  flutter_staggered_grid_view: ^0.7.0
  markdown: ^7.2.1
  flutter_highlight: ^0.7.0
  markdown_widget: ^2.3.2+3
  loading_indicator: ^3.1.0
  go_router: ^13.2.0
  logger: ^2.1.0
  sqflite: ^2.3.2
  image_picker: ^1.0.7
  file_picker: ^6.2.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_lints:
  hive_generator: ^2.0.0
  json_serializable: ^6.5.1
  build_runner:
  flutter_test:
    sdk: flutter